### ISSUE TITLE
Question regarding explanation

### ISSUE THREAD

**Issue by niksy** [zoubin/realpathify#1]
Can you provide example for the problem this plugin solves? I’m trying to see if this problem can crop up easily or is just a edge case. I suppose browserify-handbook would mention it explictly if it’s a common problem.

> However, transforms applied in browserify won't work on modules whose resolved paths containing node_modules by default. So, if you symlink your local modules in node_modules, you probably have to figure out some way to make transforms applied to them.
> 
> This module presents a way to do that, by hacking b._bresolve, to make it resolve symlinked subdirectories in node_modules to their real paths, so module-deps won't treat them as global modules, and apply transforms to them.

**Comment by zoubin** [comment]
I believe browserify has already fixed it in this [commit](https://github.com/substack/node-browserify/commit/504832b4b9fde30c36877122b265ddccbea7be77).
